[phases.setup]
nixPkgs = ['python39', 'python39Packages.pip']

[phases.install]
cmds = ['cd server && python -m pip install -r requirements.txt']

[phases.build]
cmds = ['cd server && python manage.py collectstatic --noinput']

[start]
cmd = 'cd server && python manage.py migrate && gunicorn server.wsgi --bind 0.0.0.0:$PORT'
