[phases.setup]
nixPkgs = ['python3', 'python3Packages.pip', 'python3Packages.setuptools']

[phases.install]
cmds = ['cd server && pip3 install -r requirements.txt']

[phases.build]
cmds = ['cd server && python3 manage.py collectstatic --noinput']

[start]
cmd = 'cd server && python3 manage.py migrate && gunicorn server.wsgi --bind 0.0.0.0:$PORT'
