# Generated by Django 4.2.23 on 2025-09-09 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_investor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_type', models.CharField(choices=[('equity', 'Equity Pool'), ('refinance', 'Refinance Pool')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('funded', 'Funded'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('address_line', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('percent_owned', models.DecimalField(decimal_places=2, max_digits=5)),
                ('co_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('property_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('property_link', models.URLField(blank=True, null=True)),
                ('mortgage_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('roi_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term', models.CharField(choices=[('6', '6 Months'), ('12', '12 Months'), ('24', '24 Months'), ('custom', 'Custom')], default='12', max_length=10)),
                ('custom_term_months', models.PositiveIntegerField(blank=True, null=True)),
                ('other_property_loans', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('credit_card_debt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_debt_payments', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('home_insurance_doc', models.CharField(blank=True, max_length=500, null=True)),
                ('tax_return_doc', models.CharField(blank=True, max_length=500, null=True)),
                ('appraisal_doc', models.CharField(blank=True, max_length=500, null=True)),
                ('property_photos', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='server.borrower')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
