# Generated by Django 4.2.23 on 2025-10-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_investment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='full_name',
        ),
        migrations.AddField(
            model_name='borrower',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrower',
            name='last_name',
            field=models.CharField(default='User', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrower',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='borrower',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=20),
            preserve_default=False,
        ),
    ]
