# Generated by Django 4.2.23 on 2025-10-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_remove_borrower_full_name_borrower_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='address_line_1',
            field=models.CharField(default='Unknown', help_text='Street address line 1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pool',
            name='address_line_2',
            field=models.CharField(blank=True, help_text='Street address line 2 (optional)', max_length=255),
        ),
        migrations.AddField(
            model_name='pool',
            name='date_of_birth',
            field=models.DateField(default='1990-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pool',
            name='email',
            field=models.EmailField(default='unknown@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pool',
            name='fico_score',
            field=models.PositiveIntegerField(blank=True, help_text='Credit score (optional)', null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pool',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pool',
            name='mailing_city',
            field=models.CharField(default='Unknown', help_text='City', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pool',
            name='mailing_country',
            field=models.CharField(default='United States', max_length=100),
        ),
        migrations.AddField(
            model_name='pool',
            name='mailing_state',
            field=models.CharField(default='Unknown', help_text='State', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pool',
            name='mailing_zip_code',
            field=models.CharField(default='00000', help_text='ZIP code', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pool',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pool',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pool',
            name='prior_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pool',
            name='prior_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pool',
            name='prior_middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pool',
            name='ssn',
            field=models.CharField(default='000-00-0000', help_text='Social Security Number for identity verification', max_length=11),
            preserve_default=False,
        ),
    ]
