# Generated by Django 4.2.23 on 2025-10-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_pool_address_line_1_pool_address_line_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='co_owners',
            field=models.JSONField(blank=True, default=list, help_text='List of co-owner information'),
        ),
        migrations.AddField(
            model_name='pool',
            name='existing_loans',
            field=models.JSONField(blank=True, default=list, help_text='List of existing loans on property'),
        ),
        migrations.AddField(
            model_name='pool',
            name='primary_address_choice',
            field=models.CharField(blank=True, help_text='Primary residence choice: primary, vacant, tenant, owner-occupied', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='property_links',
            field=models.JSONField(blank=True, default=list, help_text='List of property links'),
        ),
    ]
