# Generated by Django 4.2.23 on 2025-10-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_pool_co_owners_pool_existing_loans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='is_custom_term',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pool',
            name='loan_type',
            field=models.CharField(blank=True, choices=[('interest-only', 'Interest-Only'), ('maturity', 'Maturity')], max_length=20, null=True),
        ),
    ]
