# Generated by Django 4.2.23 on 2025-10-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_pool_is_custom_term_pool_loan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='liabilities',
            field=models.JSONField(blank=True, default=list, help_text='Array of liability objects with type, amount, monthlyPayment, remainingBalance'),
        ),
    ]
