# Generated by Django 4.2.23 on 2025-10-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_add_liabilities_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='term_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
