# Generated by Django 4.2.23 on 2025-10-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_pool_term_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='ssn',
            field=models.CharField(help_text='Social Security Number for identity verification', max_length=15),
        ),
    ]
