# Generated by Django 4.2.23 on 2025-10-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_add_email_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('user_type', models.CharField(choices=[('borrower', 'Borrower'), ('investor', 'Investor')], max_length=10)),
                ('user_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='borrower',
            old_name='is_email_verified',
            new_name='email_verified',
        ),
        migrations.RenameField(
            model_name='investor',
            old_name='is_email_verified',
            new_name='email_verified',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='email_verification_sent_at',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='email_verification_sent_at',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='email_verification_token',
        ),
    ]
